export const REQUEST_GET_MOVIES = 'REQUEST_GET_MOVIES';
export const SUCCESS_GET_MOVIES = 'SUCCESS_GET_MOVIES';
export const FAILURE_GET_MOVIES = 'FAILURE_GET_MOVIES';
export const MOVIES_LOADING = 'MOVIES_LOADING';