export const REQUEST_GET_MOVIES = 'REQUEST_GET_MOVIES';
export const SUCCESS_GET_MOVIES = 'SUCCESS_GET_MOVIES';
export const FAILURE_GET_MOVIES = 'FAILURE_GET_MOVIES';
export const REQUEST_GET_WATCHLIST = 'REQUEST_GET_WATCHLIST';
export const SUCCESS_GET_WATCHLIST = 'SUCCESS_GET_WATCHLIST';
export const FAILURE_GET_WATCHLIST = 'FAILURE_GET_WATCHLIST';
